### ISSUE TITLE
Change path of txt files - Permissions.

### ISSUE THREAD

**Issue by saitoh183** [jamesmontemagno/MyStreamTimer#20] opened 2020-04-25 07:06 UTC
@jamesmontemagno 
Currently all files are in C:\ProgramData\MyStreamTimer

could you allow use to save these in a custom location?

**Comment by jamesmontemagno** [comment] 2020-04-29 19:19
Not currently today, but I will update it with an option somewhere.

**Comment by jamesmontemagno** [comment] 2020-05-27 04:55
I just rolled this feature out on macOS. Working to add it to Windows next.

**Comment by timboxyz** [comment] 2020-10-31 12:21
> I just rolled this feature out on macOS. Working to add it to Windows next.

I tried using a RAMdrive to save multiple SSD writes but I get a permission error on Catalina, chmod 777 but same result.

**Comment by timboxyz** [comment] 2020-11-01 11:46
> > I just rolled this feature out on macOS. Working to add it to Windows next.
> 
> I tried using a RAMdrive to save multiple SSD writes but I get a permission error on Catalina, chmod 777 but same result.
> There is no option to add the app to 'Files & Folders' in Security & Privacy. Only Full disk access which is risky.

Actually any location I have tried apart from the default seems to produce a permissions error.

**Comment by jamesmontemagno** [comment] 2020-11-01 18:32
Maybe i need to add somethign to the info.plist hmmmm I will check it out.

**Comment by timboxyz** [comment] 2021-01-04 16:13
Just wondering if the OSX permissions issues will get fixed since this is issue now closed?

**Comment by jamesmontemagno** [comment] 2021-01-04 17:42
I'll take a look as I thought it worked on macOS alright on my end. On Windows it isn't possible. I may just not allow it at all.

**Comment by timboxyz** [comment] 2021-01-05 10:35
If it does work on your system it would be great to work out what is different. Even with "Full Disk Access" selected for it I still get a permission denied error.

**Comment by jamesmontemagno** [comment] 2021-10-29 22:22
You should just have to do -> https://github.com/jamesmontemagno/MyStreamTimer#macos-files-cant-be-saved

**Comment by jeremiasmanninen** [comment] 2021-10-30 05:19
I tried to say that giving "Full disk access" did not get it working for me. I am still having the same problem.

**Comment by jamesmontemagno** [comment] 2021-10-31 01:14
@jeremiasmanninen  what seems to be your actual isssue. can you share some screenshots of what is working and what isn't so I can try to reproduce it here.

**Comment by jeremiasmanninen** [comment] 2021-11-01 10:50
@jamesmontemagno Here is a screenshot. I did everything as https://github.com/jamesmontemagno/MyStreamTimer#macos-files-cant-be-saved say
![Näyttökuva 2021-11-1 kello 12 47 36](https://user-images.githubusercontent.com/81366427/139660554-757640b5-b597-4d3e-9eb0-1cd8cd543c1c.png)
s.

**Comment by jeremiasmanninen** [comment] 2021-11-01 10:57
And when I restarted MyStreamTimer app I got that:
![Näyttökuva 2021-11-1 kello 12 56 40](https://user-images.githubusercontent.com/81366427/139661379-258b16b7-04f8-4f24-b249-463764756c65.png)

**Comment by jamesmontemagno** [comment] 2021-11-01 22:59
Are you changing things in the "About" what if you reset it to the normal path?

It looks like at some point it worked because it has the files in there....

**Comment by jeremiasmanninen** [comment] 2021-11-02 05:26
I copied the files from original path. It works well when using original
path after resetting. The problem why I want to use different path is that
I want to share the timer txt-file on my local network.

ti 2.11.2021 klo 0.59 James Montemagno ***@***.***> kirjoitti:

**Comment by timboxyz** [comment] 2021-11-02 10:31
These are exactly the behaviours I exoerience. Anything other than the default path

gives rise to the permissions error even with full file access granted to the application.

 

Resetting the path to the default restores functionality. In my case the alternative (desired)

path is not a network drive though but a local RamDisk.

 

 

--
Tim

 
 

Sent: Tuesday, November 02, 2021 at 5:26 AM

**Comment by jamesmontemagno** [comment] 2021-11-02 15:55
Gotcha! I will take a look at this.

**Comment by jamesmontemagno** [comment] 2022-02-26 03:00
Should be good in the latest version. I have a new "verify" button for the patch changes on macOS and seems to be working well for me.

**Comment by timboxyz** [comment] 2022-02-26 12:18
I have updated to the latest version from Apple Store. I can see the verify button but unfortunately, it's still rejecting the path I have set even with "Full Disk Acess" set.
See the attached. Note I can "cd" to the path in a Terminal window and have full disk access set
<img width="597" alt="Screenshot 2022-02-26 at 12 14 11" src="https://user-images.githubusercontent.com/58913363/155842790-249ff87b-2f10-4a4c-a1a9-eb51fdcc3f7c.png">

**Comment by timboxyz** [comment] 2022-02-26 20:53
Using the default means frequent writing to an SSD which I would rather avoid and there doesn't seem to be any other version than the App Store.

Pity there is no workaround to the sandboxing. Other 3rd party App Store Apps pop up a permissions box the first time you try and access a particular path so there must be some way round it.

**Comment by jamesmontemagno** [comment] 2022-02-27 00:48
I'll hook up an external drive to it and double check again on my end and see if I can get it working. It is a strange one that is for sure.

**Comment by jamesmontemagno** [comment] 2022-02-27 05:47
@timboxyz i think maybe I figured it out... I think i needed to add more permissions to allow external drives. Doing some testing and will report back.

**Comment by jamesmontemagno** [comment] 2022-02-27 05:47
Also, let me know if you want to be a TestFlight tester. Just shoot me your email.

**Comment by timboxyz** [comment] 2022-02-27 12:43
> @timboxyz i think maybe I figured it out... I think i needed to add more permissions to allow external drives. Doing some testing and will report back.

I did try changing the default path to point to the top level of my folders (/Users/tim/) on the main drive and got the same issue.

I have messaged my email via Twitter to avoid exposing it here.

**Comment by timboxyz** [comment] 2022-03-01 12:01
Still a slight oddity if trying to use the root level of a drive, it's not surviving restarts, a subfolder is fine though.
<img width="614" alt="Screenshot 2022-03-01 at 11 52 51" src="https://user-images.githubusercontent.com/58913363/156165595-f933fb46-78cf-4df1-a2e4-17740c5b3ce5.png">

**Comment by jamesmontemagno** [comment] 2022-03-01 21:00
oh gotcha... i will try this out... so if you do "/Volumes/G-DRIVE-2/MySteramTimer" then it will survive restarts?

**Comment by timboxyz** [comment] 2022-03-02 10:51
> oh gotcha... i will try this out... so if you do "/Volumes/G-DRIVE-2/MySteramTimer" then it will survive restarts?

Yes, will check new TestFLight.

**Comment by jamesmontemagno** [comment] 2022-03-03 04:00
I'll keep testing it out. I didn't have any issues with my usb drive that I plugged in, but I will check it out more. You said it works fine if you pick the folder again though from the about page.

Also no issues at all with a sub-folder?

**Comment by timboxyz** [comment] 2022-03-03 13:46
No issues with sub folder, only top level of drive. Works ok once you repick.
-- 
Tim

**Comment by jamesmontemagno** [comment] 2022-03-03 18:16
very very interesting, will keep testing out :)

**Comment by timboxyz** [comment] 2022-03-08 18:55
Just tried the new Test fight version. Still not surviving restarts.
However, I no longer get the double error window now, with the non-closable underneath one saying "Do not show this message again", just the top one as shown above which closes when clicked on.

**Comment by timboxyz** [comment] 2022-03-09 20:18
I am wondering what format your pen drive is? My Ramdrive is HFS+ but I got the same result with a FAT RamDrive.

**Comment by jamesmontemagno** [comment] 2022-03-09 20:34
i'll take a look on that and see.

**Comment by timboxyz** [comment] 2022-03-23 18:13
Tested 2.5.0 (39) Seems OK provided you stay clear of the root folder. works with DOS and HFS+ disk images. I notice that on restart it populates the working folder with a full set of blank files which I don't recall it doing before but it's not an issue.

**Comment by jamesmontemagno** [comment] 2022-03-23 23:13
@timboxyz  thanks for testing. It was always supposed to populate the folder with all the files, but it was broken before ;) and now fixed!

I put in a not about staying away from the root folder as I have no idea how to fix that as it "should just work" but I will get this published live. Thank you for all the testing :)

**Closed** 2022-05-04 17:58 UTC
Labels: in-progress, windows

**Comment by timboxyz** [comment] 2022-06-28 17:44
FYI I have just noticed other apps having issues writing to the root of a Ramdisk (permission denied type issues) although finder can drag files to it.

I suspect an oddity in MacOS.
